AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GXPAPI

  Sample SAM Template for GXPAPI

## More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Parameters:
  Environment:
    Description: Sub environment to deploy the application
    Type: String
    Default: ''
    # AllowedValues:
    #   - staging
    #   - production
    # - staging
    #   - production
  SubEnv:
    Type: String
    Default: ''
    Description: Sub environment to deploy the application
    MaxLength: 30

  CognitoID:
    Type: String
    Description: cognito deployment
  
  ClientID:
    Type: String
    Description: cognito client id

Globals:
  Function:
    Timeout: 600
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        ENV: !Sub ${Environment}
        COGNITO : !Sub ${CognitoID}
        CLIENT : !Sub ${ClientID}
        APIGATEWAY : !Ref MyApi
        # BUCKETNAME : !Ref S3BranchBucket

Conditions:
  CustomDomains: !Equals [!Ref Environment, "dev"]

  SchedulerOn: 
    Fn::Or:
      - Fn::Equals:
          - !Ref Environment
          - dev
      - Fn::Equals:
          - !Ref Environment
          - staging
      - Fn::Equals:
          - !Ref Environment
          - prod

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler  # Specify the Lambda handler function
      Runtime: python3.9  # Choose the runtime (Python 3.9 in this case)
      CodeUri: ./src/aws_lambda  # Path to the directory containing the Lambda function code
      MemorySize: 128  # Memory allocated to the function (128MB)
      Timeout: 5  # Function timeout in seconds
      Policies: 
        - AWSLambdaBasicExecutionRole  # Provides basic permissions to the Lambda function
      Environment: 
        Variables: 
          EXAMPLE_ENV_VAR: "value"  # Add any environment variables here if needed
Outputs:
  HelloWorldFunctionOutput:
    Description: "Lambda function ARN"
    Value: !GetAtt HelloWorldFunction.Arn